### ISSUE TITLE
I want to archive old information

### ISSUE THREAD

**Issue by renatolond** [rafaelwmartins/meu-ponto#7]
If #6 existed, changing rounding methods would make my old history no longer make sense. I want to be able to archive old information so that it is available only for visualization, but is no longer calculated according to the options selected.

**Comment by rafaelwmartins** [comment]
I see. In fact this is something very difficult to implement today because everything is calculated dynamically; only the actual entries are being stored.

Therefore, although I believe this is useful, it is not worth the effort. Sorry. :smile:
